FROM ubuntu:20.04

WORKDIR /home/

RUN apt-get update \
    && apt-get install -y python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m pip install -U pip setuptools wheel

COPY . .

RUN pip3 install .
RUN pip3 install .[test]

CMD ["pytest"]
